# -*- coding: utf-8 -*-
"""N/w_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWMu1j4HNtdh-sJ4pJaPQIotT5dBZ2f6

# Phase 1 — Export MongoDB logs to CSV for model training
Network Monitoring & Predictive Failure System  (export_logs.py)
"""



# Run this code in local machine
import os
import pandas as pd
from datetime import datetime

# ── Load environment variables ────────────────────────────
try:
    from dotenv import load_dotenv
    load_dotenv()
    print(".env loaded")
except Exception:
    print(" dotenv not found — make sure MONGO_URI is set in environment")

# ── Connect to MongoDB ────────────────────────────────────
try:
    import pymongo
except ImportError:
    print("pymongo not installed. Run: pip install pymongo dnspython")
    exit(1)

MONGO_URI = os.getenv("MONGO_URI")

if not MONGO_URI:
    print("MONGO_URI not found in .env file")
    exit(1)

print(" Connecting to MongoDB Atlas...")

try:
    client = pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=5000)
    client.admin.command("ping")
    print("MongoDB connected successfully")
except Exception as e:
    print(f" MongoDB connection failed: {e}")
    exit(1)

# ── Fetch logs ────────────────────────────────────────────
db = client["network_monitor"]
logs_collection = db["logs"]

print(" Fetching logs from MongoDB...")

try:
    logs = list(logs_collection.find({}, {"_id": 0}))  # exclude _id field
    print(f" Fetched {len(logs)} log entries")
except Exception as e:
    print(f" Failed to fetch logs: {e}")
    exit(1)

if len(logs) == 0:
    print(" No logs found in the database. Make sure your monitor has been running.")
    exit(1)

# ── Convert to DataFrame ──────────────────────────────────
print(" Converting to DataFrame...")

df = pd.DataFrame(logs)

# ── Check expected columns ────────────────────────────────
expected_columns = ["timestamp", "node_name", "ip", "network_type", "state", "latency", "fails"]
missing = [col for col in expected_columns if col not in df.columns]

if missing:
    print(f"  Missing columns: {missing}")
    print(f"   Available columns: {list(df.columns)}")
else:
    print("All expected columns found")

# ── Data Cleaning ─────────────────────────────────────────
print(" Cleaning data...")

# Keep only expected columns (ignore any extras)
df = df[[col for col in expected_columns if col in df.columns]]

# Convert timestamp to datetime if not already
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Drop rows where latency is null (ping failed rows)
before = len(df)
df = df.dropna(subset=["latency"])
after = len(df)
print(f"   Removed {before - after} rows with null latency")

# Convert latency to float (safety)
df["latency"] = df["latency"].astype(float)

# Convert fails to int (safety)
df["fails"] = df["fails"].fillna(0).astype(int)

# Sort by node_name + timestamp (important for feature engineering)
df = df.sort_values(["node_name", "timestamp"]).reset_index(drop=True)

# ── Summary Stats ─────────────────────────────────────────
print("\n Dataset Summary:")
print(f"   Total rows        : {len(df)}")
print(f"   Unique nodes      : {df['node_name'].nunique()}")
print(f"   Date range        : {df['timestamp'].min()} → {df['timestamp'].max()}")
print(f"   Network types     : {df['network_type'].unique().tolist()}")
print(f"\n   State distribution:")
print(df["state"].value_counts().to_string())
print(f"\n   Latency stats (ms):")
print(df["latency"].describe().round(3).to_string())

# ── Save to CSV ───────────────────────────────────────────
OUTPUT_FILE = "logs.csv"

print(f"\nSaving to {OUTPUT_FILE}...")
df.to_csv(OUTPUT_FILE, index=False)
print(f"Saved {len(df)} rows to {OUTPUT_FILE}")
print(f"\n Done! Upload '{OUTPUT_FILE}' to Google Colab to begin training.")
print(f"   File location: {os.path.abspath(OUTPUT_FILE)}")

"""Network Node Failure Predictor, Random Forest Classifier

    - **Cell 1** — Install & Import Libraries,
    - **Cell 2** — Upload & Load logs.csv,
    - **Cell 3** — Data Cleaning,
    - **Cell 4** — Feature Engineering,
    - **Cell 5** — Label Creation (will_fail_soon),
    - **Cell 6** — Train / Test Split,
    - **Cell 7** — Train Random Forest,
    - **Cell 8** — Evaluate Model,
    - **Cell 9** — Feature Importance Plot,
    - **Cell 10** — Save & Download model.pkl
"""

# Install Libraries
!pip install scikit-learn pandas matplotlib seaborn

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score ,classification_report ,confusion_matrix ,f1_score
from sklearn.preprocessing import LabelEncoder
print(' All libraries imported successfully')

# Cell 2 — Upload & Load logs.csv,Upload your logs.csv file from your local machine or from google.colab import files
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Network Monitoring & Predictive Failure System/model/logs.csv')
print(f'\\n Loded {len(df):,} rows and {len(df.columns)} columns')
print(f'\\n Columns: {list(df.columns)}')
print(f'\\n First 5 rows:')
df.head()

# Cell 3 — Data Cleaning
print('Cleaning data...\\n')

# convert timestamp--------------------------------------------
df['timestamp'] = pd.to_datetime(df['timestamp'])

#drop nulls-----------------------------------------------------
before = len(df)
df = df.dropna(subset=['latency','state','node_name'])
after = len(df)
print(f'Removed {before - after} rows with null latency')

#Fix data types---------------------------------------------------
df['latency'] = df['latency'].astype(float)
df['fails']   = df['fails'].fillna(0).astype(int)

# Encode network_type ---------------------------------------------
# wifi=0, router=1, ethernet=2, other=3
network_map = {'wifi': 0, 'router': 1, 'ethernet': 2}
df['network_type_encoded'] = df['network_type'].map(network_map).fillna(3).astype(int)

# Encode state---------------------------------------------------
# UP=0, DEGRADED=1, DOWN=2
state_map = {'UP': 0, 'DEGRADED': 1, 'DOWN': 2}
df['state_encoded'] = df['state'].map(state_map).fillna(0).astype(int)

# Sort by node + time (CRITICAL for rolling features)------------------------
df = df.sort_values(['node_name', 'timestamp']).reset_index(drop=True)

# Summary--------------------------------------------------------------
print(f'\\n Clean dataset: {len(df):,} rows')
print(f'\\n State Distribution:')
print(df['state'].value_counts())
print(f'\\nNetwork Types:')
print(df['netork_type'].value_counts())
print(f'\\nLatency Stats (ms):')
print(df['latency'].describe().round(3))
df.head()

# Cell 4 — Feature Engineering Creating predictive features per node using rolling windows

print(' Engineering features...\\n')
# Group by node for rolling calculations----------------------------------------------------
df = df.sort_values(['node_name', 'timestamp']).reset_index(drop=True)

# Rolling window size (last 5 readings per node)
WINDOW = 5

# Feature 1: Rolling Average Latency (last 5 readings)--------------------------------------
df['rolling_avg_latency'] = df.groupby('node_name')['latency'].transform(lambda x: x.rolling(window=WINDOW, min_periods=1).mean())
# Feature 2: Rolling Max Latency (last 5 readings)------------------------------------------
df['rolling_max_latency'] =   df.groupby('node_name')['latency'].transform(lambda x: x.rolling(window=WINDOW, min_periods=1).max())
# Feature 3: Rolling Std Latency (last 5 readings)-----------------------------------------# High std = unstable connection
df['rolling_std_latency'] =  df.groupby('node_name')['latency'].transform(lambda x: x.rolling(window=WINDOW, min_periods=1).std().fillna(0))
# Feature 4: Latency Trend (current - previous)------------------------------------# Positive = getting worse, Negative = improving
df['latency_trend'] = df.groupby('node_name')['latency'].transform(lambda x: x.diff().fillna(0))
#  Feature 5: Fail Count (already in data)-------------------------------------# Already exists as 'fails' column
# Feature 6: Rolling Fail Sum (last 5 readings)
df['rolling_fail_sum'] = df.groupby('node_name')['fails'] .transform(lambda x: x.rolling(window=WINDOW, min_periods=1).sum())
# Feature 7: Previous State-------------------------------------------
df['prev_state_encoded'] = df.groupby('node_name')['state_encoded'].transform(lambda x: x.shift(1).fillna(0))
# Feature 8: Time in Current State (seconds)-------------------------
def time_in_state(group):
    result = []
    last_change_time = group['timestamp'].iloc[0]
    last_state = group['state'].iloc[0]

    for _, row in group.iterrows():
        if row['state'] != last_state:
            seconds = (row['timestamp'] - last_change_time).total_seconds()
            result.append(seconds)

            last_change_time = row['timestamp']
            last_state = row['state']
        else:
            result.append(0)

    return pd.Series(result, index=group.index)


# Apply function
df['time_in_state_sec'] = df.groupby('node_name', group_keys=False).apply(time_in_state)

print(' Features created:')

features = [
    'rolling_avg_latency',
    'rolling_max_latency',
    'rolling_std_latency',
    'latency_trend',
    'rolling_fail_sum',
    'prev_state_encoded',
    'network_type_encoded',
    'time_in_state_sec'
]

for f in features:
    print(f'   ✔ {f}')

print('\n Sample with features:')
print(df[features].head(10))

# Cell 5 — Label Creation. will_fail_soon = 1` if node goes DOWN within next 3 log entries
print(' Creating labels...\\n')
# Look ahead N steps to see if node goes DOWN
LOOKAHEAD = 3

def will_fail_soon(group):
    """For each row, check if the node goes DOWN within the next LOOKAHEAD rows (per node).
    Returns: 1 = failure coming, 0 = safe
    """
    states = group['state'].values
    labels = []

    for i in range(len(states)):
        future = states[i+1 : i+1+LOOKAHEAD]

        if 'DOWN' in future:
            labels.append(1)  # failure coming soon
        else:
            labels.append(0)  # safe

    return pd.Series(labels, index=group.index)

df['will_fail_soon'] = df.groupby('node_name', group_keys=False).apply(will_fail_soon)

#  Label Distribution----------------------------------------------------------
label_counts = df['will_fail_soon'].value_counts()
total = len(df)
print(f' Label Distribution:')
print(f'   Safe (0)           : {label_counts.get(0, 0):,} rows ({label_counts.get(0, 0)/total*100:.1f}%)')
print(f'   Failure Soon (1)   : {label_counts.get(1, 0):,} rows ({label_counts.get(1, 0)/total*100:.1f}%)')

# Visualize Label Distribution--------------------------------------------------
plt.figure(figsize=(6, 4))
colors = ['#2ecc71', '#e74c3c']
label_counts.plot(kind='bar', color=colors, edgecolor='black')
plt.title('Label Distribution: will_fail_soon', fontsize=14, fontweight='bold')
plt.xlabel('Label (0=Safe, 1=Failure Soon)')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('label_distribution.png', dpi=150)
plt.show()
print('\\n Labels created successfully')

# Cell 6 — Train / Test Split
print('  Preparing train/test split...\n')

# Define Features (X) and Target (y)---------------------------------------------------------
FEATURES = [
    'rolling_avg_latency',
    'rolling_max_latency',
    'rolling_std_latency',
    'latency_trend',
    'fails',
    'rolling_fail_sum',
    'prev_state_encoded',
    'state_encoded',
    'network_type_encoded',
    'time_in_state_sec'
]

TARGET = 'will_fail_soon'

# Drop any remaining NaN rows---------------------------------------------------------
df_model = df[FEATURES + [TARGET]].dropna()
print(f'   Rows used for training: {len(df_model):,}')

X = df_model[FEATURES]
y = df_model[TARGET]

# Split: 80% Train, 20% Test---------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f'\nSplit complete:')
print(f'   Training set   : {len(X_train):,} rows (80%)')
print(f'   Testing set    : {len(X_test):,} rows (20%)')

print(f'\n   Training label distribution:')
print(f'   Safe (0)       : {(y_train == 0).sum():,}')
print(f'   Failure (1)    : {(y_train == 1).sum():,}')

# Cell 7 — Train Random Forest
print('Training Random Forest Classifier...\n')

# Model Configuration---------------------------------------------------------
model = RandomForestClassifier(
    n_estimators=100,        # 100 decision trees
    max_depth=10,            # max depth per tree
    random_state=42,         # reproducible results
    class_weight='balanced', # handle imbalanced UP/DOWN ratio
    n_jobs=-1,               # use all CPU cores
    verbose=0
)

# Train---------------------------------------------------------------
print('   Training in progress...')
model.fit(X_train, y_train)

print('\n Model trained successfully!')
print(f'   Trees in forest    : {model.n_estimators}')
print(f'   Features used      : {model.n_features_in_}')
print(f'   Classes            : {model.classes_}')

# Cell 8 — Evaluate Model
print('📊 Evaluating model...\n')

# Predictions---------------------------------------------------------------
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # probability of failure

# Core Metrics---------------------------------------------------------------
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print('=' * 45)
print(f'  Accuracy     : {accuracy*100:.2f}%')
print(f'  F1 Score     : {f1*100:.2f}%')
print('=' * 45)
print()

print(' Full Classification Report:')
print(classification_report(
    y_test,
    y_pred,
    target_names=['Safe (0)', 'Failure Soon (1)']
))

# Confusion Matrix---------------------------------------------------------------
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(7, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Predicted Safe', 'Predicted Failure'],
    yticklabels=['Actual Safe', 'Actual Failure']
)

plt.title('Confusion Matrix', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

# Interpretation---------------------------------------------------------------
tn, fp, fn, tp = cm.ravel()

print(f'\n Result Breakdown:')
print(f'   True Negatives  (correctly predicted Safe)    : {tn:,}')
print(f'   True Positives  (correctly predicted Failure) : {tp:,}')
print(f'   False Positives (false alarms)                : {fp:,}')
print(f'   False Negatives (missed failures)             : {fn:,}')

# Pass/Fail Check---------------------------------------------------------------
print(f'\n🎯 Target vs Achieved:')
print(f'   Accuracy  → Target: >85%  | Got: {accuracy*100:.1f}%  {"✅" if accuracy > 0.85 else " Below target"}')
print(f'   F1 Score  → Target: >82%  | Got: {f1*100:.1f}%  {"✅" if f1 > 0.82 else " Below target"}')

# Cell 9 — Feature Importance Plot.  Feature Importance
print('📈Plotting feature importance...\\n')
importances = model.feature_importances_

feature_df = pd.DataFrame({
    'Feature': FEATURES,
    'Importance': importances
}).sort_values('Importance', ascending=True)

# Plot---------------------------------------------------------
plt.figure(figsize=(10, 6))

colors = [
    '#e74c3c' if i == len(feature_df) - 1 else '#3498db'
    for i in range(len(feature_df))
]

plt.barh(
    feature_df['Feature'],
    feature_df['Importance'],
    color=colors,
    edgecolor='black'
)

plt.xlabel('Importance Score', fontsize=12)
plt.title(
    '🌲 Random Forest — Feature Importance\n(Which features help predict failure most?)',
    fontsize=13,
    fontweight='bold'
)

plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150)
plt.show()

# Print rankings---------------------------------------------------------
print('\n📊 Feature Rankings:')

for _, row in feature_df.sort_values('Importance', ascending=False).iterrows():
    bar = '█' * int(row['Importance'] * 100)
    print(f'   {row["Feature"]:30s} {bar} {row["Importance"]:.4f}')

# Cell 10 — Save & Download model.pkl
print(' Saving model...\\n')

# Save model-----------------------------------------
MODEL_PATH = 'model.pkl'

with open(MODEL_PATH, 'wb') as f:
    pickle.dump({
        'model': model,
        'features': FEATURES,
        'version': '1.0',
        'accuracy': round(accuracy * 100, 2),
        'f1_score': round(f1 * 100, 2)
    }, f)

print(f'Model saved as {MODEL_PATH}')
print(f'   Accuracy : {accuracy*100:.2f}%')
print(f'   F1 Score : {f1*100:.2f}%')
print(f'   Features : {len(FEATURES)}')

# Download (only works in Google Colab)-----------------------------------------
try:
    from google.colab import files

    files.download(MODEL_PATH)
    files.download('confusion_matrix.png')
    files.download('feature_importance.png')
    files.download('label_distribution.png')

    print('\n Done! Files downloaded:')
except ImportError:
    print('\nNot running in Colab — skipping file download.')

print('    model.pkl              → place in project/model/ folder')
print('    confusion_matrix.png   → for your report')
print('    feature_importance.png → for your report')
print('    label_distribution.png → for your report')

print('\n Next Step: Build predictor.py to use this model in your app!')