# -*- coding: utf-8 -*-
"""N/w_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWMu1j4HNtdh-sJ4pJaPQIotT5dBZ2f6

# Phase 1 — Export MongoDB logs to CSV for model training
Network Monitoring & Predictive Failure System  (export_logs.py)
"""

# ==============================
# 📦 1. IMPORTS
# ==============================
import pandas as pd
import numpy as np
import pickle
import time
import warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score
)

# ==============================
# ⚙️ 2. CONFIG
# ==============================
WINDOW = 10
LOOKAHEAD = 6
THRESHOLD = 0.4
MODEL_PATH = "modelV3.pkl"

# ==============================
# 📥 3. LOAD DATA
# ==============================
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Network Monitoring & Predictive Failure System/model/updated_logs.csv")

# ==============================
# 🧹 CLEAN DATA
# ==============================
print("🧹 Cleaning data...")
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['fails'] = df['fails'].fillna(0).astype(int)

# Create ping failure flag FIRST
df['ping_failed'] = df['latency'].isna().astype(int)

# Replace failed ping latency
df['latency'] = df['latency'].fillna(-1)

# Convert to float
df['latency'] = df['latency'].astype(float)

# Encode network_type
network_map = {'wifi': 0, 'router': 1, 'ethernet': 2}
df['network_type_encoded'] = df['network_type'].map(network_map).fillna(3).astype(int)

# Sort properly
df = df.sort_values(['node_name', 'timestamp']).reset_index(drop=True)

# ==============================
# 🔥 STEP 1: Inject failure sequences (MAIN LOGIC)
# ==============================
import numpy as np

for node in df['node_name'].unique():
    node_idx = df[df['node_name'] == node].index

    failure_starts = np.random.choice(
        node_idx[:-5],
        size=max(1, len(node_idx)//40),
        replace=False
    )

    for start in failure_starts:

        seq_idx = range(start, min(start + 6, node_idx[-1] + 1))

        for i, idx in enumerate(seq_idx):

            # Early instability
            if i == 0:
                df.loc[idx, 'latency'] += np.random.randint(20, 40)

            # Rising instability
            elif i == 1:
                df.loc[idx, 'latency'] += np.random.randint(40, 80)

            # Packet-loss beginning
            elif i == 2:
                df.loc[idx, 'latency'] += np.random.randint(80, 140)
                df.loc[idx, 'fails'] += 1

            # Degraded state
            elif i == 3:
                df.loc[idx, 'state'] = 'DEGRADED'
                df.loc[idx, 'latency'] += np.random.randint(150, 250)

            # Severe degradation
            elif i == 4:
                df.loc[idx, 'state'] = 'DEGRADED'
                df.loc[idx, 'latency'] += np.random.randint(250, 400)
                df.loc[idx, 'fails'] += 2

            # Actual failure
            elif i >= 5:
                df.loc[idx, 'state'] = 'DOWN'
                df.loc[idx, 'latency'] = -1
                df.loc[idx, 'fails'] += 3
                df.loc[idx, 'ping_failed'] = 1


# ==============================
# ✅ STEP 3: Encode AFTER ALL changes
# ==============================
state_map = {'UP': 0, 'DEGRADED': 1, 'DOWN': 2}
df['state_encoded'] = df['state'].map(state_map).fillna(0).astype(int)

# ==============================
# 📊 Check distribution
# ==============================
print("\nUpdated State Distribution:")
print(df['state'].value_counts(normalize=True))

# ==============================
# ⚙️ 5. FEATURE ENGINEERING
# ==============================
print("⚙️ Engineering features...")

df['rolling_avg_latency'] = df.groupby('node_name')['latency'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).mean()
)

df['rolling_max_latency'] = df.groupby('node_name')['latency'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).max()
)

df['rolling_std_latency'] = df.groupby('node_name')['latency'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).std().fillna(0)
)

df['latency_trend'] = df.groupby('node_name')['latency'].diff().fillna(0)

df['latency_acceleration'] = df.groupby('node_name')['latency_trend'].diff().fillna(0)
df['latency_volatility'] = df.groupby('node_name')['latency'].transform(
    lambda x: x.diff().abs().rolling(WINDOW, min_periods=1).mean()
)
df['rolling_fail_sum'] = df.groupby('node_name')['fails'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).sum()
)

df['latency_ratio'] = np.where(
    df['rolling_avg_latency'] > 0,
    df['latency'] / (df['rolling_avg_latency'] + 1e-5),
    0
)
df['fail_rate'] = df['rolling_fail_sum'] / WINDOW
df['ping_failed_rate'] = df.groupby('node_name')['ping_failed'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).mean()
)
df['is_unstable'] = (
    (df['rolling_std_latency'] > 40) |
    (df['ping_failed_rate'] > 0.2)
).astype(int)




# Time in state
def time_in_state(group):
    result = []
    last_time = group['timestamp'].iloc[0]
    last_state = group['state'].iloc[0]

    for _, row in group.iterrows():
        if row['state'] != last_state:
            last_time = row['timestamp']
            last_state = row['state']
        result.append((row['timestamp'] - last_time).total_seconds())

    return pd.Series(result, index=group.index)

df['time_in_state_sec'] = df.groupby('node_name', group_keys=False).apply(time_in_state)

# ==============================
# 🎯 6. LABEL CREATION
# ==============================
print("🎯 Creating labels...")

def will_fail_soon(group):
    states = group['state'].values
    labels = []

    for i in range(len(states)):
        future = states[i+1:i+1+LOOKAHEAD]
        labels.append(1 if 'DOWN' in future else 0)

    return pd.Series(labels, index=group.index)

df['will_fail_soon'] = df.groupby('node_name', group_keys=False).apply(will_fail_soon)

print(df['will_fail_soon'].value_counts(normalize=True))

# ==============================
# ✂️ 7. TRAIN / TEST SPLIT
# ==============================
FEATURES = [
    'rolling_avg_latency',
    'rolling_max_latency',
    'rolling_std_latency',
    'latency_trend',
    'latency_acceleration',
    'latency_volatility',
    'rolling_fail_sum',
    'network_type_encoded',
    'time_in_state_sec',
    'latency_ratio',
    'fail_rate',
    'is_unstable',
    'ping_failed',
    'ping_failed_rate'
]

TARGET = 'will_fail_soon'

df_model = df[FEATURES + [TARGET]].dropna()

X = df_model[FEATURES]
y = df_model[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ==============================
# 🌲 8. MODEL TRAINING
# ==============================
print("🌲 Training model...")

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=8,
    min_samples_leaf=3,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)




print("\n🚀 Training Configuration")
print(f"Trees                : {model.n_estimators}")
print(f"Max Depth            : {model.max_depth}")
print(f"Window Size          : {WINDOW}")
print(f"Prediction Horizon   : {LOOKAHEAD}")
print(f"Training Samples     : {len(X_train)}")
print(f"Testing Samples      : {len(X_test)}")
print(f"Features Used        : {len(FEATURES)}")
start_time = time.time()
model.fit(X_train, y_train)
end_time = time.time()

print(f"\n⏱️ Training Time: {end_time - start_time:.2f} sec")

# ==============================
# 📊 9. EVALUATION
# ==============================
print("📊 Evaluating model...")


y_prob = model.predict_proba(X_test)[:, 1]
y_pred = (y_prob >= 0.4).astype(int)

accuracy = accuracy_score(y_test, y_pred)
f1_weighted = f1_score(y_test, y_pred, average='weighted')
f1_failure = f1_score(y_test, y_pred, pos_label=1)

print(f"\nAccuracy       : {accuracy:.4f}")
print(f"F1 (weighted)  : {f1_weighted:.4f}")
print(f"F1 (failure)   : {f1_failure:.4f}")

print("\n📋 Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

if cm.shape == (2, 2):
    tn, fp, fn, tp = cm.ravel()
elif cm.shape == (1, 1):
    # This means only one class is present in y_true and y_pred.
    # Given previous output, it's class '0' (no failures).
    tn = cm[0, 0]
    fp, fn, tp = 0, 0, 0
else:
    # Fallback for unexpected shapes, though unlikely for binary classification
    print("Unexpected confusion matrix shape:", cm.shape)
    tn, fp, fn, tp = (0, 0, 0, 0) # Assign default values to avoid error

print("\n📌 Breakdown:")
print(f"TP: {tp} | FP: {fp} | FN: {fn} | TN: {tn}")

# ==============================
# 💾 11. SAVE MODEL
# ==============================
print("💾 Saving model...")

with open(MODEL_PATH, "wb") as f:
    pickle.dump({
        "model": model,
        "features": FEATURES,
        "threshold": THRESHOLD,
        "version": "3.0"
    }, f)

print(f"✅ Model saved → {MODEL_PATH}")

"""# **CONFUSION MATRIX**"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix

def plot_confusion_matrix(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()

    plt.figure(figsize=(6, 5))
    plt.imshow(cm)
    plt.title("Confusion Matrix (Failure Prediction)", fontsize=14)
    plt.colorbar()

    labels = np.array([
        [f"TN\n{tn}", f"FP\n{fp}"],
        [f"FN\n{fn}", f"TP\n{tp}"]
    ])

    for i in range(2):
        for j in range(2):
            plt.text(j, i, labels[i, j],
                     ha='center', va='center', fontsize=12)

    plt.xticks([0,1], ["Safe", "Failure"])
    plt.yticks([0,1], ["Safe", "Failure"])
    plt.xlabel("Predicted")
    plt.ylabel("Actual")

    plt.tight_layout()
    plt.show()

plot_confusion_matrix(y_test, y_pred)

"""# **METRICS BAR CHART**"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def plot_metrics(y_test, y_pred):
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    metrics = [accuracy, precision, recall, f1]
    names = ['Accuracy', 'Precision', 'Recall', 'F1 Score']

    plt.figure(figsize=(8, 5))
    bars = plt.bar(names, metrics)

    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval,
                 f'{yval:.2f}', ha='center', va='bottom')

    plt.title("Model Performance Metrics", fontsize=14)
    plt.ylim(0, 1)
    plt.tight_layout()
    plt.show()

plot_metrics(y_test, y_pred)

"""# **FEATURE IMPORTANCE (CLEAN + HIGHLIGHT TOP)**"""

def plot_feature_importance(model, features):
    importances = model.feature_importances_
    indices = np.argsort(importances)
    plt.figure(figsize=(8, 6))
    plt.barh(range(len(indices)), importances[indices])

    plt.yticks(range(len(indices)), [features[i] for i in indices])
    plt.xlabel("Importance")
    plt.title("Feature Importance (What drives failure?)")

    plt.tight_layout()
    plt.show()

plot_feature_importance(model, FEATURES)

"""# **FAILURE PROBABILITY DISTRIBUTION**"""

def plot_probability_distribution(probabilities):
    plt.figure(figsize=(7, 4))
    plt.hist(probabilities, bins=30)

    plt.title("Failure Probability Distribution")
    plt.xlabel("Predicted Probability")
    plt.ylabel("Frequency")

    plt.tight_layout()
    plt.show()

y_prob = model.predict_proba(X_test)[:, 1]
plot_probability_distribution(y_prob)

"""# **STATE DISTRIBUTION (FOR PPT)**"""

def plot_state_distribution(df):
    counts = df['state'].value_counts()

    plt.figure(figsize=(6, 4))
    plt.bar(counts.index, counts.values)

    for i, v in enumerate(counts.values):
        plt.text(i, v, str(v), ha='center')

    plt.title("State Distribution")
    plt.xlabel("State")
    plt.ylabel("Count")

    plt.tight_layout()
    plt.show()

plot_state_distribution(df)

# predictor.py

import pickle
import pandas as pd
import numpy as np

MODEL_PATH = "/content/modelV3.pkl"
WINDOW = 10

# ==============================
# 🔹 Load Model
# ==============================
def load_model():
    with open(MODEL_PATH, "rb") as f:
        data = pickle.load(f)

    return data["model"], data["features"], data.get("threshold", 0.5)

model, FEATURES, THRESHOLD = load_model()

print("✅ Model loaded successfully")
try:
    importances = model.feature_importances_

    print("\n📊 Feature Importance:")
    for name, imp in sorted(zip(FEATURES, importances), key=lambda x: x[1], reverse=True):
        print(f"{name:<25} : {imp:.4f}")

except Exception:
    pass
print(f"📌 Features expected: {len(FEATURES)}")

# ==============================
# 🔹 Feature Builder
# ==============================
def build_features(df):
    df = df.copy()

    # --- Validation ---
    required_cols = ['timestamp', 'latency', 'fails', 'state', 'network_type', 'node_name']
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"❌ Missing column: {col}")

    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values("timestamp")

    df['latency'] = df['latency'].fillna(-1)
    df['ping_failed'] = (df['latency'] == -1).astype(int)
    df['rolling_avg_latency'] = df.groupby('node_name')['latency'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).mean()
    )

    df['rolling_max_latency'] = df.groupby('node_name')['latency'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).max()
    )

    df['rolling_std_latency'] = df.groupby('node_name')['latency'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).std().fillna(0)
    )

    df['latency_trend'] = df.groupby('node_name')['latency'].diff().fillna(0)

    df['latency_acceleration'] = df.groupby('node_name')['latency_trend'].diff().fillna(0)
    df['latency_volatility'] = df.groupby('node_name')['latency'].transform(
    lambda x: x.diff().abs().rolling(WINDOW, min_periods=1).mean()
)
    df['rolling_fail_sum'] = df.groupby('node_name')['fails'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).sum()
    )

    df['latency_ratio'] = np.where(
    df['rolling_avg_latency'] > 0,
    df['latency'] / (df['rolling_avg_latency'] + 1e-5),
    0
    )
    df['fail_rate'] = df['rolling_fail_sum'] / WINDOW

    df['ping_failed_rate'] = df.groupby('node_name')['ping_failed'].transform(
    lambda x: x.rolling(WINDOW, min_periods=1).mean()
)

    df['is_unstable'] = (
    (df['rolling_std_latency'] > 40) |
    (df['ping_failed_rate'] > 0.2)
    ).astype(int)



    # --- Time in state ---
    times = []
    last_time = df['timestamp'].iloc[0]
    last_state = df['state'].iloc[0]

    for _, row in df.iterrows():
        if row['state'] != last_state:
            last_time = row['timestamp']
            last_state = row['state']
        times.append((row['timestamp'] - last_time).total_seconds())

    df['time_in_state_sec'] = times

    # --- Network encoding ---
    net_map = {'wifi': 0, 'router': 1, 'ethernet': 2}
    df['network_type_encoded'] = df['network_type'].map(net_map).fillna(3)

    return df

# ==============================
# 🔹 Prediction Function
# ==============================
def predict_failure(df, debug=False):
    df = build_features(df)

    # --- Ensure enough history ---
    if len(df) < WINDOW:
        raise ValueError(f"❌ Not enough data points (need at least {WINDOW} rows)")

    latest = df.iloc[-1]

    missing_features = [f for f in FEATURES if f not in latest.index]

    if missing_features:
      raise ValueError(f"❌ Missing engineered features: {missing_features}")

    # --- Align features safely ---
    X = pd.DataFrame([latest])[FEATURES]

    # --- Predict ---
    prob = model.predict_proba(X)[0][1]
    prediction = int(prob >= THRESHOLD)

    if prob >= 0.8:
      risk = "CRITICAL"
    elif prob >= 0.6:
      risk = "HIGH"
    elif prob >= 0.4:
      risk = "MEDIUM"
    else:
      risk = "LOW"
    result = {
    "failure_probability": float(round(prob, 4)),
    "prediction": prediction,
    "risk_level": risk,
    "alert": "🚨 FAILURE RISK!" if prediction else "✅ SAFE"
    }

    if debug:
        print("\n🔍 Debug Info:")
        print(X.T)
        print(f"Threshold: {THRESHOLD}")

    return result

# ==============================
# 🔹 Batch Prediction (NEW)
# ==============================
def predict_batch(df):
    df = build_features(df)
    X = df[FEATURES]

    probs = model.predict_proba(X)[:, 1]
    preds = (probs >= THRESHOLD).astype(int)

    df_result = df.copy()
    df_result["failure_probability"] = probs
    df_result["prediction"] = preds

    return df_result

# ==============================
# 🔹 Example Usage
# ==============================
if __name__ == "__main__":
    df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Network Monitoring & Predictive Failure System/model/updated_logs.csv")
    df['timestamp'] = pd.to_datetime(df['timestamp'])

    # Take last 10 logs of one node
    node_df = df[df['node_name'] == df['node_name'].iloc[0]].tail(10)

    result = predict_failure(node_df, debug=True)

    print("\n🔍 Prediction Result:")
    print(result)